menu:
  首页: /
  文章: /list/
  关于: /about/
  标签: /tags/
  分类: /categories/

showInMenu:
  - 文章
  - 关于
  - 标签
  - 分类

index:
  header:
    - "学无止境，行者无疆"
  hitokoto: false
  footer: d_q_g@live.com
  titlePosition: left
  width: small
  list: true

footerLink:
  info: © 2026 东青的博客
  友链: /friends/
  关于: /about/

post:
  footer: ""
  themeInfo: false
  width: middle
  titlePosition: center

favicon: /img/favicon.png
isRoundedAvatar: false
isAvatarRotating: false
displayTitleInTab: true

tool:
  darkMode: true
  returnToTop: true
  returnToLast: true
  topToc: true
  leftToc: true
  recentUpdatePost: true

indexInfo:
  allWordCount: true
  allViewCount: true

postInfo:
  updateDate: true
  wordCount: true
  readTime: true
  viewCount: true
  prevAndNextLink:
    status: true
    prevInfo: 上一篇
    nextInfo: 下一篇
  endContent: 以上

listInfo:
  enable: true
  hoverStyle: underline
  hoverColor: "#4f7dde"
  animationDuration: 800

cdn:
  enable: false
  choose: zzko

color:
  enable: false

imageShow:
  enable: false

font:
  enable: false

lightgallery:
  thumbnail: true
  zoom: true
  rotate: true
  autoplay: true
  fullScreen: true
  pager: false

comment:
  enable: false

inject:
  css: css/custom.css

baseElement:
  href:
  target:

version: v2.0.1
